### ISSUE TITLE
im got error when i input x86

### ISSUE THREAD

**Issue by m4k4ss4rh4ck3r** [UndeadSec/Debinject#2]
Insert the target arch x86 or x64: 

debinject > x86
Traceback (most recent call last):
  File "debinject.py", line 97, in <module>
    setArch()
  File "debinject.py", line 49, in setArch
    call('cp Utils/x86/control /tmp/evil/work/DEBIAN')
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child

**Comment by lucasduete** [comment]
Something in commit cc18662 ended up breaking the code in some executions, return to commit dda705a , to solve run :


- To discard changes made by the user  
```
git checkout -- .
```

- To return commit: 
```
git checkout dda705a
```
