### ISSUE TITLE
Error after typing system arch in call from subprocess 

### ISSUE THREAD

**Issue by MazenElzanaty** [UndeadSec/Debinject#3]
debinject > x86
Traceback (most recent call last):
  File "debinject.py", line 97, in <module>
    setArch()
  File "debinject.py", line 49, in setArch
    call('cp Utils/x86/control /tmp/evil/work/DEBIAN')
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

in call from subprocess

**Comment by lucasduete** [comment]
Duplicate of #2
